---
environment_variables:
  IMAGE_VERSION: "2025.1-ubuntu_noble-1"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: platform/openstack-keystone
docker_tags:
  - "${IMAGE_VERSION}"
  - "latest"
docker_no_cache: true
