---
# OpenStack custom images for SUNET Platform
# Each image adds wrapper scripts for secret injection from Kubernetes Secrets
clean_workspace: true
git:
  branch: main
triggers:
  cron: "@daily"

extra_jobs:
  # Keystone with OIDC support
  - name: openstack-keystone
    builders:
      - docker
    docker_name: platform/openstack-keystone
    docker_context_dir: keystone
    docker_tags:
      - "2025.1-ubuntu_noble-2"
      - "latest"

  # Heat with oslo-secrets-wrapper for memcache keys
  - name: openstack-heat
    builders:
      - docker
    docker_name: platform/openstack-heat
    docker_context_dir: heat
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # Glance with oslo-secrets-wrapper for memcache keys
  - name: openstack-glance
    builders:
      - docker
    docker_name: platform/openstack-glance
    docker_context_dir: glance
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # Cinder with oslo-secrets-wrapper for memcache keys
  - name: openstack-cinder
    builders:
      - docker
    docker_name: platform/openstack-cinder
    docker_context_dir: cinder
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # Nova with oslo-secrets-wrapper for memcache keys
  - name: openstack-nova
    builders:
      - docker
    docker_name: platform/openstack-nova
    docker_context_dir: nova
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # Placement with oslo-secrets-wrapper for memcache keys
  - name: openstack-placement
    builders:
      - docker
    docker_name: platform/openstack-placement
    docker_context_dir: placement
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"

  # Neutron with oslo-secrets-wrapper for memcache keys
  - name: openstack-neutron
    builders:
      - docker
    docker_name: platform/openstack-neutron
    docker_context_dir: neutron
    docker_tags:
      - "2025.1-ubuntu_noble-1"
      - "latest"
